name: Test Stuff

on:
  push: {}

environment:
  name: ${{ github.ref_name }}
  url: 'https://mhu.dev'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Environment
        run: env

      - name: Print sekrit
        run: echo "$TOKEN" | base64
