name: Test Stuff

on:
  push: {}

env:
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
      url: 'https://mhu.dev'
    steps:
      - name: Environment
        run: env | sort
      - name: Print sekrit
        run: echo "$TOKEN" | base64
