name: Test Stuff

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
      url: 'https://mhu.dev'
    steps:
      - name: Environment
        run: env

      - name: Print sekrit
        run: echo "$TOKEN" | base64
